-- AM CREATING EMPLOYEE TABLE
CREATE TABLE EMPLOYEE(id int, [name] varchar(100))
GO
INSERT INTO EMPLOYEE VALUES(1,'John');
GO
INSERT INTO EMPLOYEE VALUES(2,'Raj');
GO
INSERT INTO EMPLOYEE VALUES(3,'Michael');
GO
INSERT INTO EMPLOYEE VALUES(4,'Steph');
GO
-- AM CREATING EMPLOYEE DETAILS TABLE
CREATE TABLE EMPLOYEEDET(Empid int, Desig varchar(100))
GO
INSERT INTO EMPLOYEEDET VALUES(4,'Manager');
GO
INSERT INTO EMPLOYEEDET VALUES(3,'Lead');
GO
INSERT INTO EMPLOYEEDET VALUES(2,'Analyst');
GO
INSERT INTO EMPLOYEEDET VALUES(1,'Developer');
GO
SELECT * FROM EMPLOYEE
GO
SELECT * FROM EMPLOYEEDET
GO
-- RETRIEVEING EMPLOYEES INFORMATION, IF ANY OF THEIR ID IS GREATER THAN THE ID FROM THE SUBQUERY
SELECT ID,[Name] FROM EMPLOYEE WHERE ID > ANY
(SELECT Empid FROM EMPLOYEEDET WHERE Desig = 'Developer')
GO
-- RETRIEVEING EMPLOYEES INFORMATION, IF ANY OF THEIR ID IS EQUAL TO THE ID FROM THE SUBQUERY
SELECT ID,[Name] FROM EMPLOYEE WHERE ID = ANY
(SELECT Empid FROM EMPLOYEEDET WHERE Desig = 'Developer')
GO
-- RETRIEVEING EMPLOYEES INFORMATION, IF ANY OF THEIR ID IS LESSER THAN THE ID FROM THE SUBQUERY
SELECT ID,[Name] FROM EMPLOYEE WHERE ID < ANY
(SELECT Empid FROM EMPLOYEEDET WHERE Desig = 'DGM')
GO
-- ANY OPERATOR WITH NOT EQUAL TO
SELECT ID,[Name] FROM EMPLOYEE WHERE ID != ANY
(SELECT Empid FROM EMPLOYEEDET WHERE Desig = 'Developer')
